### This file acts as the global config across the website.
### Any variables in this file can be accessed in other files using
###    `{{ site.variable }}`


######################
# Site configuration #
######################
# This title will display across the website
title: "Civil Service LGBT+ Network"
# This description is predominantly for Search Engine Optimisation
description: "The Civil Service LGBT+ Network helps to create a more diverse, inclusive and equal place to work for lesbian, gay, bisexual and trans civil servants."
# Instead of "author", have the organisation name as the default
author: "Civil Service LGBT+ Network"
organisation: "Civil Service LGBT+ Network"
email: "info@civilservice.lgbt"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000"

git-repos: "https://github.com/civilservicelgbt"
site-repo: "/civilservicelgbt.github.io"
site-repo--branch: "master"
images-repo: "/images"
images-repo--branch: "main"
documents-repo: "/documents"
documents-repo--branch: "main"

#########################
# Social media accounts #
#########################
social-media-accounts:
  - account: "Facebook"
    url: "//facebook.com/civilservicelgbt"
    display-text: "Like us on Facebook"
    alt-text: "Visit our Facebook profile page"
    handle: "civilservicelgbt" # Automatically pre-pends http://facebook.com/
    hidden: false
  - account: "Twitter"
    url: "//twitter.com/cslgbt" # Twitter handle i.e. joebloggs
    display-text: "Follow us on Twitter"
    alt-text: "Visit our Twitter profile page"
    handle: "cslgbt" # Twitter handle i.e. joebloggs
    hidden: false
  - account: "Flickr"
    url:  "//www.flickr.com/photos/civilservicelgbt/"
    display-text: "Find us on Flickr"
    alt-text: "Visit our Flickr profile page"
    handle:  "civilservicelgbt"
    hidden: false
  - account: "Instagram"
    url:  "//www.instagram.com/civilservicelgbt"
    display-text: "Follow us on Instagram"
    alt-text: "Visit our Instagram profile page"
    handle:  "civilservicelgbt"
    hidden: false
  - account: "Youtube"
    url: "//youtube.com/"
    display-text: "Subscribe to us on Youtube"
    alt-text: "Visit our Youtube profile page"
    handle: ""
    hidden: true

###################
# Header settings #
###################
# This title will show in the main menu bar
header-menu--title--display-text: "Civil Service LGBT+"
# If this theme is being used for a subdomain (i.e. blog.civilservice.lgbt) then set
# - `header-menu--subdomain-title` to 'true'
# - `header-menu--subdomain-title--display-text` to any string value (i.e. "Image maker")
header-menu--subdomain-title: false
header-menu--subdomain-title--display-text: "Website Theme"

header-menu--links--hidden: false
# Header menu links
header-menu--links:
  - display-text: "Home"
    alt-text: "Visit the home page"
    url: "/"
    hidden: true
  - display-text: "News"
    alt-text: "Visit the News page"
    url: "/news"
    hidden: false
  - display-text: "Events"
    alt-text: "Visit the Events page"
    url: "/events"
    hidden: false
  - display-text: "Topics"
    alt-text: "Visit the Topics page"
    url: "/topics"
    hidden: false
  - display-text: "Publications"
    alt-text: "Visit the Publications page"
    url: "/publications"
    hidden: false
  - display-text: "Consultations"
    alt-text: "Visit the Consultations page"
    url: "/consultations"
    hidden: false
  - display-text: "Networks"
    alt-text: "Visit the Networks page"
    url: "/networks"
    hidden: false
  - display-text: "About"
    alt-text: "Learn more about us"
    url: "/about"
    hidden: false
  - display-text: "Join us"
    alt-text: "Visit the membership registration page"
    url: "/join-us"
    hidden: false

###################
# Footer settings #
###################
# This title will show in the main menu bar
footer--title--display-text: "Civil Service LGBT+ Network"

# This text will be displayed at the bottom of the website.
footer--production-notice: "Website created by <a href='//www.johnpe.art' title='Visit John Peart’s website (Opens in new window)' target='_blank' rel='noopener noreferrer'>John Peart</a>."
footer--copyright-notice: "All content is released under the <a href='https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/' title='Read more about the Open Government License. (Opens in new window)' target='_blank'>Open Government License</a> unless otherwise stated. Please attribute our work."

# Footer menu links
footer-menu--links:
  - display-text: "Become a member"
    alt-text: "Join the Civil Service LGBT+ Network as a member"
    url: "/join-us"
    hidden: false
  - display-text: "Update your profile"
    alt-text: "Update your contact details and preferences"
    url: "/update-profile"
    hidden: false
  - display-text: "Contact us"
    alt-text: "Get our contact details"
    url: "/about/contact-us"
    hidden: false
  - display-text: "About"
    alt-text: "Learn more about us"
    url: "/about"
    hidden: true
  - display-text: "Your data"
    alt-text: "Read our data and privacy policy"
    url: "/about/your-data"
    hidden: false
  - display-text: "Archived posts"
    alt-text: "View archived news posts"
    url: "/archives"
    hidden: false

# Toggle home page blocks
home-news:			true
home-events:		true
home-publications:	true
home-consultations:	true
home-topics:		true


###############
# Asset paths #
###############
# General paths
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"

# Favicons and social graph
social-media-image: "/assets/images/site/social-media.png"
favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"
theme-colour: "#e6007e"



##################################
# Analytics and domain ownership #
##################################
# Google settings
google-site-verification: "RA-YBjxyRYVSuSFAYLKkufs6gjme6kMcihoB2KgKrTA"
google-analytics: "UA-47423042-2" # GA ID code
google-analytics-domain: ".www.civilservice.lgbt"

##############
# Newsletter #
##############
# Mailchimp
unsubscribe-form: "https://us17.admin.mailchimp.com/lists/designer/?id=118945"

###############
# Collections #
###############
#This is the default permalink for the "_posts" folder.
permalink: /:year/:month/:day/:title:output_ext

collections:
  pages:
    output: true
    permalink: /:path/
    defaults:
      values:
        layout: format/page
        admin:
          add-to-collection: true
          show-in-formats: true
  archives:
    output: true
    permalink: /archives/:year/:month/:day/:title/
    defaults:
      values:
        layout: format/news
        admin:
          add-to-collection: false
          show-in-formats: false
  news:
    output: true
    permalink: /news/:year/:month/:day/:title/
    defaults:
      values:
        layout: format/news
        admin:
          add-to-collection: true
          show-in-formats: true
  publications:
    output: true
    permalink: /publication/:title/
    defaults:
      values:
        layout: format/publication
        admin:
          add-to-collection: true
          show-in-formats: true
  consultations:
    output: true
    permalink: /consultation/:title/
    defaults:
      values:
        layout: format/consultation
        admin:
          add-to-collection: true
          show-in-formats: true
  events:
    output: true
    permalink: /event/:title/
    defaults:
      values:
        layout: format/event
        admin:
          add-to-collection: true
          show-in-formats: true
  notices:
    output: true
    permalink: /notice/:title/
    defaults:
      values:
        layout: format/notice
        admin:
          add-to-collection: true
          show-in-formats: true
  topics:
    output: true
    permalink: /:title/
    defaults:
      values:
        layout: format/topic
        admin:
          add-to-collection: true
          show-in-formats: true
  team:
    output: true
    permalink: /our-team/:title/
    defaults:
      values:
        layout: format/page
        admin:
          add-to-collection: true
          show-in-formats: true
  rules:
    output: true
    permalink: /our-rules/:title/
    defaults:
      values:
        layout: format/publication
        admin:
          add-to-collection: true
          show-in-formats: false
  forum:
    output: true
    permalink: /discuss/:title/
    defaults:
      values:
        layout: format/publication
        admin:
          add-to-collection: true
          show-in-formats: false
  membership:
    output: true
    permalink: /membership/:title/
    defaults:
      values:
        layout: format/page
        admin:
          add-to-collections: true
          show-in-formats: false
  programmes:
    output: true
    permalink: /programmes/:title/
    defaults:
      values:
        layout: format/page
        admin:
          add-to-collection: true
          show-in-formats: false
  contact:
    output: true
    permalink: /contact/:title/
    defaults:
      values:
        layout: format/page
        admin:
          add-to-collection: false
          show-in-formats: false
  admin:
    output: true
    permalink: /membership/:title/
    defaults:
      values:
        layout: format/page
        admin:
          add-to-collection: false
          show-in-formats: false

defaults:
  - scope:
      path: "store"
    values:
      document: true
  - scope:
      path: "store"
    values:
      image: true
##################
# Build settings #
##################
# remote_theme: civilservicelgbt/theme
permalink: pretty
markdown: kramdown
future: false
highlighter: rouge
sass:
  sass_dir: _sass

plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/